import test from 'node:test';
import assert from 'node:assert/strict';
import { Document, Packer, Paragraph, ImageRun, Table, TableRow, TableCell } from 'docx';
import AdmZip from 'adm-zip';
import fs from 'node:fs';
import path from 'node:path';
import { testDatabase } from '../test/database';
import { persistSource, parseSource, loadAuthorizedAsset, sha256 } from './sources';
import { exportWordToBuffer } from '../export/service';
import { syntheticPdf } from '../test/pdf';

test('originals, immutable image parses, authorized export and failure preservation on PostgreSQL', async (t) => {
  const { prisma, dataDir } = await testDatabase(t);
  const a = await prisma.user.create({ data: { username: 'source-a', password: 'synthetic', status: 'active' } });
  const b = await prisma.user.create({ data: { username: 'source-b', password: 'synthetic', status: 'active' } });
  const project = await prisma.project.create({ data: { ownerId: a.id, projectCode: 'SOURCE-A', name: '合成图文项目' } });
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j7ioAAAAASUVORK5CYII=', 'base64');
  const input = await Packer.toBuffer(new Document({ sections: [{ children: [new Paragraph('合成文档，保留图片与表格'), new Paragraph({ children: [new ImageRun({ type: 'png', data: png, transformation: { width: 32, height: 32 } })] }), new Table({ rows: [new TableRow({ children: [new TableCell({ children: [new Paragraph('表格内容')] })] })] })] }] }));
  const source = await persistSource(prisma, { projectId: project.id }, a.id, '同名文件.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', input);
  const another = await persistSource(prisma, { projectId: project.id }, a.id, '同名文件.docx', source.mimeType, input);
  assert.notEqual(source.id, another.id); assert.equal(source.sha256, another.sha256);
  const first = await parseSource(prisma, source.id, a.id);
  assert.match(first.markdown, /表格内容/); assert.equal(first.assets?.length, 1, JSON.stringify(first.warnings));
  const asset = await loadAuthorizedAsset(prisma, a.id, first.assets![0].assetId, project.id);
  await assert.rejects(loadAuthorizedAsset(prisma, b.id, first.assets![0].assetId), /无项目访问权限/);
  const exported = await exportWordToBuffer({ project_name: '图片验收', outline: [{ id: '1', title: '图文', content: first.markdown }], assetResolver: async (id) => ({ buffer: (await loadAuthorizedAsset(prisma, a.id, id, project.id)).buffer, type: 'png' }) });
  const media = new AdmZip(exported.buffer).getEntries().filter((entry) => /^word\/media\/.*\.png$/.test(entry.entryName));
  assert.equal(media.length, 1); assert.equal(sha256(media[0].getData()), asset.asset.sha256);
  const second = await parseSource(prisma, source.id, a.id);
  assert.equal(second.parseVersion, 2);
  assert.equal(sha256((await loadAuthorizedAsset(prisma, a.id, first.assets![0].assetId)).buffer), asset.asset.sha256);
  assert.equal(sha256(fs.readFileSync(path.join(dataDir, source.relativePath))), source.sha256);
  const broken = await persistSource(prisma, { projectId: project.id }, a.id, '损坏.docx', source.mimeType, Buffer.from('not-a-zip'));
  await assert.rejects(parseSource(prisma, broken.id, a.id));
  assert.equal(fs.readFileSync(path.join(dataDir, broken.relativePath)).toString(), 'not-a-zip');
  assert.equal((await prisma.documentParseVersion.findFirstOrThrow({ where: { sourceId: broken.id } })).status, 'error');
  assert.equal(await prisma.documentAsset.count({ where: { parse: { sourceId: broken.id } } }), 0);
  const textPdf = await persistSource(prisma, { projectId: project.id }, a.id, '文本.pdf', 'application/pdf', syntheticPdf(false));
  assert.match((await parseSource(prisma, textPdf.id, a.id)).markdown, /Synthetic procurement requirements/);
  const scan = await persistSource(prisma, { projectId: project.id }, a.id, '扫描.pdf', 'application/pdf', syntheticPdf(true));
  await assert.rejects(parseSource(prisma, scan.id, a.id), /OCR|文字/);
  assert.equal(sha256(fs.readFileSync(path.join(dataDir, scan.relativePath))), scan.sha256);
});
