import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import AdmZip from 'adm-zip';
import { testDatabase } from '../test/database';
import { createAssetLibraryStore } from '../asset-library/store';
import { createPerformanceStore } from '../performance/store';
import { getAssetFilePath, createWorkspacePaths } from '../document/paths';
import { createBusinessStore } from './store';
import { createBusinessPackage, packageFile } from './export';
import { usableSnapshot, hashFile, type SnapshotFile } from './snapshots';
import { attachChapterReferences, validateReferenceBlocks } from './technical';
import { createTechnicalPlanStore } from '../technical-plan/store';

test('manual business confirmation, immutable source copy, technical truth and streaming Word/ZIP manifest', async (t) => {
  const { prisma } = await testDatabase(t);
  const user = await prisma.user.create({ data: { username: 'business-a', password: 'synthetic', status: 'active', modules: '["knowledge-base"]' } });
  const other = await prisma.user.create({ data: { username: 'business-b', password: 'synthetic', status: 'active', modules: '["knowledge-base"]' } });
  const project = await prisma.project.create({ data: { ownerId: user.id, projectCode: 'BIZ-A', name: '合成商务项目', bidDeadline: new Date('2026-09-08') } });
  const assets = createAssetLibraryStore(prisma); const performance = createPerformanceStore(prisma); const business = createBusinessStore(prisma);
  const fileMeta = { fileId: 'file-1', originalName: '同名原件.txt', mimeType: 'text/plain', size: 12, ext: '.txt' };
  const asset = await assets.createItem('company', { name: '合同原件', files: [fileMeta] }, user.id);
  const sourceFile = getAssetFilePath(undefined, 'company', asset.id, fileMeta.fileId, fileMeta.ext);
  await fs.mkdir(path.dirname(sourceFile), { recursive: true }); await fs.writeFile(sourceFile, 'synthetic-contract');
  const record = await performance.create({ title: '医院工程', projectType: '弱电工程', contractAmount: '1000000.21', completedAt: '2025-12-31', summary: '按合同完成系统建设与验收。', isPubliclyCitable: true, assetIds: [asset.id] }, user.id);
  const requirement = await business.createRequirement(project.id, user.id, { category: 'performance', rawText: '提供合同金额不低于一百万元的类似工程业绩', thresholds: { minimumAmount: '1000000.20', completedAfter: '2025-01-01' } });
  const candidates = await business.candidates(project.id, user.id, requirement.id, '医院'); const candidate = candidates.items[0];
  assert.equal(candidate.conclusion, 'candidate'); assert.ok(candidate.evidence.every((item) => item.state === 'met'));
  assert.equal((await business.workspace(project.id, user.id)).requirements[0].match, null, 'keyword and deterministic checks do not confirm compliance');
  const match = await business.confirm(project.id, user.id, requirement.id, { type: candidate.type, id: candidate.id, version: candidate.version, fingerprint: candidate.fingerprint, requirementVersion: requirement.version, conclusion: 'confirmed', reason: '人工已核对合同金额和完成日期', requestKey: 'confirm-once' });
  const repeated = await business.confirm(project.id, user.id, requirement.id, { requestKey: 'confirm-once' }); assert.equal(match.id, repeated.id);
  const snapshot = await usableSnapshot(prisma, match.snapshotId!, project.id, user.id, true);
  const snapshotFile = (snapshot.files as unknown as SnapshotFile[])[0]; const snapshotPath = path.join(createWorkspacePaths(project.id).workspaceDir, snapshotFile.relativePath);
  await fs.writeFile(sourceFile, 'changed-source-content');
  assert.equal(await hashFile(snapshotPath), snapshotFile.sha256, 'source replacement cannot alter confirmed bytes');
  const technical = createTechnicalPlanStore(prisma);
  await technical.saveOutline(project.id, { outlineData: { outline: [{ id: 'chapter-1', title: '类似业绩', content: '保留人工章节。' }] } });
  await technical.saveChapterContent(project.id, { nodeId: 'chapter-1', content: '保留人工章节。' });
  await attachChapterReferences(prisma, project.id, user.id, 'chapter-1', [snapshot.id]);
  const node = await prisma.technicalPlanOutlineNode.findUniqueOrThrow({ where: { projectId_nodeId: { projectId: project.id, nodeId: 'chapter-1' } } });
  assert.match(node.content, /保留人工章节/); assert.match(node.content, /1000000\.21/); assert.equal(node.manualLocked, true);
  await assert.rejects(validateReferenceBlocks(prisma, project.id, 'chapter-1', node.content.replace('1000000.21', '9000000.00')), /权威字段/);
  await technical.saveOutline(project.id, { outlineData: { outline: [{ id: 'chapter-1', title: '类似业绩', content: '模型试图覆盖' }] } });
  assert.equal((await prisma.technicalPlanOutlineNode.findUniqueOrThrow({ where: { projectId_nodeId: { projectId: project.id, nodeId: 'chapter-1' } } })).content, node.content);
  const revision = await business.createRevision(project.id, user.id, 'revision-once');
  assert.equal(revision.status, 'ready'); assert.equal((await business.createRevision(project.id, user.id, 'revision-once')).id, revision.id);
  const pkg = await createBusinessPackage(prisma, project.id, user.id, revision.id, false);
  const file = await packageFile(prisma, project.id, user.id, pkg.packageId, false);
  const zip = new AdmZip(await fs.readFile(file.file)); const manifest = JSON.parse(zip.readAsText('manifest.json'));
  assert.equal(manifest.files.length, 1); assert.equal(manifest.files[0].sha256, snapshotFile.sha256);
  assert.equal(zip.getEntries().filter((entry) => !entry.isDirectory).length, manifest.files.length + 2);
  const word = new AdmZip(zip.readFile(manifest.word.path)!); assert.match(word.readAsText('word/document.xml'), /已确认满足/);
  await assert.rejects(packageFile(prisma, project.id, other.id, pkg.packageId, false), /无项目访问权限/);
  await performance.update(record.id, { version: record.version, isPubliclyCitable: false }, user.id);
  await assert.rejects(packageFile(prisma, project.id, user.id, pkg.packageId, false), /撤销/);
  assert.equal(await hashFile(snapshotPath), snapshotFile.sha256);
  const missing = await business.createRequirement(project.id, user.id, { category: 'asset', rawText: '必须提供额外证明' });
  await business.confirm(project.id, user.id, missing.id, { requirementVersion: missing.version, conclusion: 'missing', reason: '尚缺原件' });
  await prisma.user.update({ where: { id: user.id }, data: { modules: '[]' } });
  await assert.rejects(business.candidates(project.id, user.id, missing.id), /无资料库权限/);
});
