import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { Document, Packer, Paragraph, ImageRun } from 'docx';
import AdmZip from 'adm-zip';
import { testDatabase } from '../test/database';
import { createAssetLibraryStore } from '../asset-library/store';
import { createKnowledgeBaseStore } from '../knowledge-base/store';
import { createPerformanceStore } from '../performance/store';
import { getAssetFilePath, createWorkspacePaths } from '../document/paths';
import { persistSource, parseSource, loadAuthorizedAsset, sha256 } from '../document/sources';
import { createReferenceSnapshot, usableSnapshot, snapshotHistory, type SnapshotFile } from './snapshots';
import { businessSource } from './sources';
import { exportWordToBuffer } from '../export/service';
import { createBusinessStore } from './store';
import { createBusinessPackage, packageFile } from './export';
import { createTechnicalPlanStore } from '../technical-plan/store';

test('snapshot narrative images and same-name attachments survive archive, unlink and physical source deletion; incomplete copies never publish', async (t) => {
  const { prisma, dataDir } = await testDatabase(t);
  const user = await prisma.user.create({ data: { username: 'snapshot-images', password: 'synthetic', status: 'active', modules: '["knowledge-base"]' } });
  const project = await prisma.project.create({ data: { ownerId: user.id, projectCode: 'SNAP-IMG', name: '合成引用', bidDeadline: new Date('2026-09-08') } });
  const kb = createKnowledgeBaseStore(prisma); const assets = createAssetLibraryStore(prisma); const performances = createPerformanceStore(prisma);
  const folder = await kb.createFolder('合成叙述');
  const timestamp = new Date().toISOString(); const documentId = randomUUID();
  await prisma.knowledgeDocument.create({ data: { documentId, folderId: folder.id, fileName: '图文叙述.docx', documentDir: `documents/${documentId}`, sourcePath: '', markdownPath: '', status: 'success', createdAt: timestamp, updatedAt: timestamp } });
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j7ioAAAAASUVORK5CYII=', 'base64');
  const docx = await Packer.toBuffer(new Document({ sections: [{ children: [new Paragraph('合成项目叙述'), new Paragraph({ children: [new ImageRun({ type: 'png', data: png, transformation: { width: 32, height: 32 } })] })] }] }));
  const original = await persistSource(prisma, { knowledgeDocumentId: documentId }, user.id, '图文叙述.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', docx);
  const parsed = await parseSource(prisma, original.id, user.id);
  await prisma.knowledgeItem.create({ data: { documentId, itemId: 'story', title: '实施叙述', resume: '合成', content: parsed.markdown, createdAt: timestamp, updatedAt: timestamp } });
  const files = ['one', 'two'].map((fileId) => ({ fileId, originalName: '中文同名原件.txt', ext: '.txt', mimeType: 'text/plain', size: 3, sha256: sha256(Buffer.from(fileId)) }));
  const asset = await assets.createItem('company', { name: '合同原件', files }, user.id);
  const sourcePaths = files.map((file) => getAssetFilePath(undefined, 'company', asset.id, file.fileId, file.ext));
  for (const [i, file] of sourcePaths.entries()) { await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, files[i]!.fileId); }
  let performance = await performances.create({ title: '合成医院项目', isPubliclyCitable: true, assetIds: [asset.id], documentIds: [documentId], knowledgeItems: [{ documentId, itemId: 'story' }] }, user.id);
  const source = await businessSource(prisma, 'performance', performance.id);
  const options = { projectId: project.id, userId: user.id, type: source.type, id: source.id, version: source.version, fingerprint: source.fingerprint };
  await fs.unlink(sourcePaths[0]!);
  await assert.rejects(createReferenceSnapshot(prisma, options));
  assert.equal(await prisma.projectReferenceSnapshot.count({ where: { status: 'ready' } }), 0);
  const failed = await prisma.projectReferenceSnapshot.findFirstOrThrow({ where: { status: 'error' } });
  await assert.rejects(usableSnapshot(prisma, failed.id, project.id, user.id), /未就绪/);
  await fs.writeFile(sourcePaths[0]!, 'one');
  const business = createBusinessStore(prisma);
  const requirement = await business.createRequirement(project.id, user.id, { category: 'performance', rawText: '提供项目业绩原件' });
  const match = await business.confirm(project.id, user.id, requirement.id, { ...options, requirementVersion: requirement.version, conclusion: 'confirmed', reason: '已人工核对图文及两份原件', refreshOfId: failed.id });
  const snapshot = await usableSnapshot(prisma, match.snapshotId!, project.id, user.id, true);
  const narrative = (snapshot.data as any).narrative as string;
  const copiedId = /yibiao-asset:\/\/([a-z0-9-]+)/.exec(narrative)![1]!;
  assert.notEqual(copiedId, parsed.assets![0]!.assetId);
  const before = await loadAuthorizedAsset(prisma, user.id, copiedId, project.id);
  const snapshotFiles = snapshot.files as unknown as SnapshotFile[];
  assert.equal(snapshotFiles.length, 3); assert.equal(new Set(snapshotFiles.map((file) => file.filename)).size, 3);
  await kb.deleteFolder(folder.id, user.id);
  assert.ok((await prisma.knowledgeDocument.findUniqueOrThrow({ where: { documentId } })).archivedAt);
  await assert.rejects(kb.deleteDocument(documentId, 2, user.id, true), /解除关联/);
  performance = await performances.archive(performance.id, performance.version, user.id);
  await performances.update(performance.id, { version: performance.version, assetIds: [], documentIds: [], knowledgeItems: [], team: [] }, user.id, true);
  await kb.deleteDocument(documentId, 2, user.id, true);
  await assets.deleteItem('company', asset.id, asset.version, user.id, true);
  assert.equal(await prisma.documentAsset.findUnique({ where: { id: parsed.assets![0]!.assetId } }), null);
  assert.equal(sha256((await loadAuthorizedAsset(prisma, user.id, copiedId, project.id)).buffer), sha256(before.buffer));
  assert.equal((await snapshotHistory(prisma, project.id, user.id)).find((item) => item.id === snapshot.id)!.sourceStatus, 'missing');
  const exported = await exportWordToBuffer({ project_name: '历史图文', outline: [{ id: '1', title: '项目叙述', content: narrative }], assetResolver: async (id) => ({ buffer: (await loadAuthorizedAsset(prisma, user.id, id, project.id)).buffer, type: 'png' }) });
  assert.equal(new AdmZip(exported.buffer).getEntries().filter((entry) => !entry.isDirectory && /^word\/media\//.test(entry.entryName)).length, 1);
  const revision = await business.createRevision(project.id, user.id, 'lifecycle-revision');
  const normal = await createBusinessPackage(prisma, project.id, user.id, revision.id, false);
  const normalZip = new AdmZip(await fs.readFile((await packageFile(prisma, project.id, user.id, normal.packageId, false)).file));
  const manifest = JSON.parse(normalZip.readAsText('manifest.json')); assert.equal(new Set(manifest.files.map((f: any) => f.path)).size, 3);
  await fs.unlink(path.join(createWorkspacePaths(project.id).workspaceDir, snapshotFiles[0]!.relativePath));
  await assert.rejects(createBusinessPackage(prisma, project.id, user.id, revision.id, false), /附件缺失/);
  const draft = await createBusinessPackage(prisma, project.id, user.id, revision.id, true);
  const draftZip = new AdmZip(await fs.readFile((await packageFile(prisma, project.id, user.id, draft.packageId, false)).file));
  const draftManifest = JSON.parse(draftZip.readAsText('manifest.json')); assert.equal(draftManifest.draft, true); assert.ok(draftManifest.warnings.some((warning: string) => warning.includes('缺少附件')));
});

test('business re-extraction preserves human revisions and a completed extraction job is idempotent', async (t) => {
  const { prisma } = await testDatabase(t);
  const user = await prisma.user.create({ data: { username: 'extraction-audit', password: 'synthetic', status: 'active', modules: '["knowledge-base"]' } });
  const project = await prisma.project.create({ data: { ownerId: user.id, projectCode: 'EXTRACT-AUDIT', name: '合成招标' } });
  const text = '必须提供有效营业执照。\n必须提供项目合同。';
  const original = await persistSource(prisma, { projectId: project.id }, user.id, '合成招标.txt', 'text/plain', Buffer.from(text));
  const parsed = await parseSource(prisma, original.id, user.id);
  await createTechnicalPlanStore(prisma).importTenderDocument(project.id, [parsed]);
  const business = createBusinessStore(prisma); let calls = 0;
  const ai = { requestJson: async () => { calls++; return { requirements: [{ category: 'asset', rawText: '必须提供有效营业执照。' }, { category: 'performance', rawText: '必须提供项目合同。' }] }; } };
  const job = { id: 'extract-first', projectId: project.id, userId: user.id } as any;
  const first = await business.extract(job, ai as any); const human = first.requirements[0]!;
  await business.updateRequirement(project.id, user.id, human.id, { version: human.version, rawText: '人工核定的营业执照要求', thresholds: { category: '营业执照' } });
  await business.extract(job, ai as any); assert.equal(calls, 1);
  await business.extract({ ...job, id: 'extract-second' }, ai as any);
  const state = await business.workspace(project.id, user.id);
  assert.ok(state.requirements.some((row) => row.id === human.id && row.rawText === '人工核定的营业执照要求'));
  assert.equal(state.requirements.length, 2);
  assert.equal(await prisma.auditEvent.count({ where: { sourceType: 'business-extraction', action: 'complete' } }), 2);
});
